# Generated by Django 3.1.7 on 2021-03-20 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firstapp', '0003_auto_20210303_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id_articulo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_articulo', models.CharField(blank=True, max_length=20, null=True)),
                ('precio', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'articulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id_bitacora', models.AutoField(primary_key=True, serialize=False)),
                ('id_articulo', models.IntegerField(blank=True, null=True)),
                ('nombre_nuevo', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_viejo', models.CharField(blank=True, max_length=20, null=True)),
                ('precio_nuevo', models.CharField(blank=True, max_length=20, null=True)),
                ('precio_viejo', models.CharField(blank=True, max_length=20, null=True)),
                ('usuario', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('accion', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'bitacora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('clave', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'paciente',
                'managed': False,
            },
        ),
    ]
